name: WhiteSource

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: WhiteSource CI Scan
        uses: Vonage/oss-ci-integration@v1.0
        env:
          WHITESOURCE_PRODUCT_NAME: ${{ secrets.WHITESOURCE_PRODUCT_NAME }}
          WHITESOURCE_PROJECT_NAME: ${{ env.GITHUB_REPOSITORY }}
          WHITESOURCE_GH_PAT: ${{ secrets.WHITESOURCE_GH_PAT }}
          WHITESOURCE_CONFIG_REPO: ${{ secrets.WHITESOURCE_CONFIG_REPO }}
          WHITESOURCE_NPM_TOKEN: ${{ secrets.WHITESOURCE_NPM_TOKEN }}
          WHITESOURCE_API_KEY: ${{ secrets.WHITESOURCE_API_KEY }}
          WHITESOURCE_USER_KEY: ${{ secrets.WHITESOURCE_USER_KEY }}

      - name: Display results
        if: ${{ always() }}
        run: cat ./whitesource/policyRejectionSummary.json
